# Generated by Django 5.0.6 on 2024-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0004_remove_client_contract_date_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contract_number_and_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='organization_form',
        ),
        migrations.AddField(
            model_name='client',
            name='contract_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата и номер договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='org_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организационная форма'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_address',
            field=models.CharField(max_length=255, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Система налогообложения'),
        ),
    ]
