# Generated by Django 5.0.6 on 2024-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0005_remove_client_contract_number_and_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('work_name', models.CharField(max_length=255)),
                ('time_norm', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price_category', models.CharField(choices=[('Главный бухгалтер', 'Главный бухгалтер'), ('Бухгалтер', 'Бухгалтер')], default='Бухгалтер', max_length=20)),
            ],
        ),
    ]
