# Generated by Django 5.0.6 on 2024-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0006_worktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='number',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='work_name',
        ),
        migrations.AddField(
            model_name='worktype',
            name='comments',
            field=models.TextField(default='Нет комментариев'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktype',
            name='name',
            field=models.CharField(default='Название работы', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
