# Generated by Django 5.0.6 on 2024-06-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0007_remove_worktype_number_remove_worktype_work_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='quantity',
        ),
    ]
