# Generated by Django 5.0.6 on 2024-06-25 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0008_remove_worktype_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnusualOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_content', models.TextField(verbose_name='Содержание операции')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Продолжительность минут')),
                ('operation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость операции')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client', verbose_name='Клиент')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktype', verbose_name='Ценовая категория')),
            ],
        ),
    ]
