# Generated by Django 5.0.6 on 2024-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0009_unusualoperationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unusualoperationlog',
            name='price_category',
            field=models.CharField(choices=[('Главный бухгалтер', 'Главный бухгалтер'), ('Бухгалтер', 'Бухгалтер')], max_length=20, verbose_name='Ценовая категория'),
        ),
    ]
