# Generated by Django 5.0.6 on 2024-06-25 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0010_alter_unusualoperationlog_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='unusualoperationlog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
