# Generated by Django 5.0.6 on 2024-06-26 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0011_unusualoperationlog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_norm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Норма времени')),
                ('price_category', models.CharField(max_length=20, verbose_name='Ценовая категория')),
                ('cost_per_minute', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость минуты')),
                ('operation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость операции')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client', verbose_name='Клиент')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktype', verbose_name='Вид работы')),
            ],
        ),
    ]
