# Generated by Django 5.0.6 on 2024-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0012_standardoperationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationlog',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Стоимость минуты'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='operation_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Стоимость операции'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='time_norm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Норма времени'),
        ),
    ]
