# Generated by Django 5.0.6 on 2024-06-26 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0015_alter_standardoperationlog_price_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardoperationlog',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='operation_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='price_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='time_norm',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktype'),
        ),
    ]
