# Generated by Django 5.0.6 on 2024-06-26 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0016_standardoperationlog_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardoperationlog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Стоимость минуты'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='inn',
            field=models.CharField(default=1, editable=False, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='operation_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Стоимость операции'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='price_category',
            field=models.CharField(editable=False, max_length=20, verbose_name='Ценовая категория'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='time_norm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Норма времени'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='standardoperationlog',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.worktype', verbose_name='Вид работы'),
        ),
    ]
