# Generated by Django 5.0.6 on 2024-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0017_alter_standardoperationlog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unusualoperationlog',
            name='inn',
            field=models.CharField(default=1, editable=False, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
