# Generated by Django 5.0.6 on 2024-06-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0018_unusualoperationlog_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_content', models.TextField(default='', verbose_name='Содержание записи')),
                ('reason', models.CharField(choices=[('T', 'Т – требования'), ('O', 'О – оборудование'), ('S', 'С – сырье'), ('K', 'К – квалификация')], default='T', max_length=1, verbose_name='Причина')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounting_button.client', verbose_name='Клиент')),
            ],
        ),
    ]
