# Generated by Django 5.0.6 on 2024-06-26 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0019_deviationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviationlog',
            name='operation_content',
        ),
        migrations.AddField(
            model_name='deviationlog',
            name='content',
            field=models.TextField(default=1, verbose_name='Содержание записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviationlog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='deviationlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting_button.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='deviationlog',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='deviationlog',
            name='reason',
            field=models.CharField(choices=[('Т', 'Т – требования'), ('О', 'О – оборудование'), ('С', 'С – сырье'), ('К', 'К – квалификация')], max_length=1, verbose_name='Причина'),
        ),
    ]
