# Generated by Django 5.0.6 on 2024-06-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_button', '0020_remove_deviationlog_operation_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardoperationlog',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
